# Generated by Django 2.0.5 on 2018-06-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('idteam', models.AutoField(db_column='idTeam', primary_key=True, serialize=False)),
                ('team_name', models.CharField(db_column='Team_name', max_length=45)),
            ],
            options={
                'db_table': 'Teams',
                'managed': False,
            },
        ),
    ]
