# Generated by Django 2.0.6 on 2018-06-04 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='data_wydarzenia',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 11, 4, 12, 231775, tzinfo=utc), verbose_name='Data meczu/treningu:'),
            preserve_default=False,
        ),
    ]
