# Generated by Django 2.0.6 on 2018-06-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_data_wydarzenia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Match',
        ),
    ]
