# Generated by Django 2.0.6 on 2018-06-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180604_1937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='Question',
        ),
    ]
